# Generated by Django 4.0.5 on 2022-06-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreriaWeb', '0002_alter_producto_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
