# Generated by Django 4.0.5 on 2022-06-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floreriaWeb', '0004_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='rut_vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='floreriaWeb.vendedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
